### PR TITLE
Try to load the chunk containing the tile instead of throwing the exception

### PR DESCRIPTION
**Pull request by Ifera**
Try to load the chunk containing the tile instead of throwing the exception. 
On success, add the tile. 
On failure, remove the tile and log error on console. 
DO NOT throw exception.

Should hopefully fix the crashes on creative.

### CODE REVIEW

**Review by Driesboy — APPROVED** [review]

**Comment by TobiasG-DE** [comment]
Woah Dries approved first try

**Comment by Driesboy** [comment]
That's what happens if it's good first try ;p

**Comment by TobiasG-DE** [comment]
> That's what happens if it's good first try ;p

mimimimi

**Comment by TobiasG-DE** [comment]
image

**Pull request merged**
