### PR TITLE
Fixed setSkinAdapater() not working correctly

### PR DESCRIPTION
**Pull request by Lunarelly**
setSkinAdapter() previously would set it only to the latest protocol

### CODE REVIEW

**Comment by Lunarelly** [comment]
So, when plugin will trigger ```TypeConverter::getInstance()->setSkinAdapter()``` on start, all of TypeConverters will inherit new SkinAdapter.

**Comment by dries-c** [comment]
Ideally you would set this on every instance using TypeConverter::getAll(true), since the SkinAdapter might be different depending on the version of Minecraft you're using

**Comment by Lunarelly** [comment]
i tried, but server just stucks at this point

**Comment by dries-c** [comment]
Wdym with stuck?

**Comment by Lunarelly** [comment]
it stucks for some time then crashes with memory allocation error

**Comment by Lunarelly** [comment]
anyway this way is the fastest one

**Comment by Lunarelly** [comment]
TypeConverter::getAll(true) takes like 4 seconds to finish, my version is hell lot faster

**Comment by Lunarelly** [comment]
Also it does not depend on any version u using, you setting the adapter globally, then upcoming creations of TypeConverter will inherit adapter by default

**Comment by Lunarelly** [comment]
and SkinAdapter is not any different from 1.18.10, lol

**Pull request closed without merging**
