### PR TITLE
Fix FloatingTextParticle

### PR DESCRIPTION
**Pull request by fuyutsuki**
## Introduction

Fixed a bug that FloatingTextParticle is not displayed

### Relevant issues

* 4830f9b0a90d5d3e998f3cf27c6ee7facd354037

### API changes

* `public Skin::null()` is not returns parfectly nully Skin, instead return a transparent skin modeled with `geometry.humanoid.custom`.
* `private Skin::$null` acts as a null skin cache.

### Behavioural changes

There's no impact on performance.

## Backwards compatibility

N/A

## Follow-up

N/A

## Tests

With this change, FloatingText and skin are displayed normally. Please tell me if you need precise testing.

### CODE REVIEW

**Comment by Driesboy** [comment]
The idea of this hack was fixing crashes by the client. I'll push a fix for floating texts soon.

**Comment by fuyutsuki** [comment]
Under what circumstances does a client crash occur?

**Comment by Driesboy** [comment]
I've no clue, it happens randomly. And this hack fixes most of them.

**Comment by fuyutsuki** [comment]
hmm

**Pull request closed without merging**
